name: API ZAP
on:
  schedule:
    - cron:  '0 0 1 3,6,9,12 *'
  push:
jobs:
  build:
    env:
      IMAGE_FAMILY: 'debian-9'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCSPROJECT }}
          service_account_key: ${{ secrets.GCLOUDSERVICEKEY }}
          export_default_credentials: true
      - name: get current source image
        id: source_image
        run: echo "::set-output name=SOURCE_IMAGE::$(gcloud compute images list --format='value(NAME)' --filter='family:${{ jobs.build.env.IMAGE_FAMILY }}')"
      - run: sed -e "s;%SOURCE_IMAGE%;${{ steps.source_image.outputs.SOURCE_IMAGE }};g" -e "s;%IMAGE_FAMILY%;${{ jobs.build.env.IMAGE_FAMILY }};g" template.yaml > cloudbuild.yaml
      - run: cat cloudbuild.yaml